### ISSUE TITLE
Undefined method 'compass_config'

### ISSUE THREAD

**Issue by AlexEscalante** [axyz/middleman-zurb-foundation#14]
I was able to create my project using this command:

```
$ bundle exec middleman init acme --template=axyz/middleman-zurb-foundation
```

But then:

```
$ bundle exec middleman build
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub middleman-core` to work around a system/bundle conflict.
/Users/alex/Devel/audelabs/test/acme/config.rb:5:in `evaluate_configuration!': undefined method `compass_config' for #<Middleman::ConfigContext:0x007fa78454f280> (NoMethodError)
from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.4/lib/middleman-core/application.rb:327:in `instance_eval'
from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.4/lib/middleman-core/application.rb:327:in `evaluate_configuration!'
from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.4/lib/middleman-core/application.rb:284:in `initialize'
from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.4/bin/middleman:48:in `new'
from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.4/bin/middleman:48:in `<top (required)>'
from /Users/alex/.rbenv/versions/2.2.2/bin/middleman:23:in `load'
from /Users/alex/.rbenv/versions/2.2.2/bin/middleman:23:in `<main>'
```

That warning about the bintstub seems strange, you might want to have a look into https://github.com/middleman/middleman/issues/1859 for more info about my previous issue with middleman. 

Thanks

**Comment by malford89** [comment]
Same problem here.
